# Generated by Django 2.2.3 on 2019-08-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=15)),
                ('hp', models.CharField(max_length=15, null=True)),
            ],
            options={
                'ordering': ['brand'],
            },
        ),
    ]
