# Generated by Django 2.2.3 on 2019-08-12 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_client_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date',
            new_name='date_init',
        ),
    ]
