# Generated by Django 2.2.3 on 2019-08-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190812_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='no-def', max_length=255, unique=True),
        ),
    ]
