# Generated by Django 2.2.3 on 2019-08-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_init',
            field=models.CharField(max_length=12),
        ),
    ]
